services:
  goravel:
    container_name: cek-resi-app
    image: cek-resi-app:latest
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    restart: always

  postgres:
    image: postgres:latest
    container_name: cek-resi-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: edo24123
      POSTGRES_DB: cek_resi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cek-resi-redis2
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
