networks:
  komodo_default:
    external: true
  cek_resi:
services:
  goravel:
    command: ./main
    container_name: cek-resi-app
    image: edoaurahman/cek-resi-app:latest
    ports:
      - "${APP_PORT_EXPOSE}:3000"
      - "${GRPC_PORT}:50051"
    depends_on:
      - postgres
      - redis
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_PORT_EXPOSE=${APP_PORT_EXPOSE}

      - GRPC_HOST=${GRPC_HOST}
      - GRPC_PORT=${GRPC_PORT}

      - JWT_SECRET=${JWT_SECRET}

      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}

      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}

      - SPX_TOKEN=${SPX_TOKEN}

      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
    restart: on-failure
    cpus: "0.4"
    volumes:
      - goravel:/www
      - ${CERTS_DIR:-./certs}:/www/certs
    networks:
      - komodo_default
      - cek_resi
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: cek-resi-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cek_resi
  redis:
    image: redis:7.2.7-alpine
    container_name: cek-resi-redis
    volumes:
      - redis_data:/data
    networks:
      - cek_resi
volumes:
  postgres_data:
  redis_data:
  goravel:
