// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: app/protos/resi.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackingNum   string                 `protobuf:"bytes,2,opt,name=tracking_num,json=trackingNum,proto3" json:"tracking_num,omitempty"`
	Expedition    string                 `protobuf:"bytes,3,opt,name=expedition,proto3" json:"expedition,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PackageName   string                 `protobuf:"bytes,7,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resi) Reset() {
	*x = Resi{}
	mi := &file_app_protos_resi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resi) ProtoMessage() {}

func (x *Resi) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resi.ProtoReflect.Descriptor instead.
func (*Resi) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{0}
}

func (x *Resi) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resi) GetTrackingNum() string {
	if x != nil {
		return x.TrackingNum
	}
	return ""
}

func (x *Resi) GetExpedition() string {
	if x != nil {
		return x.Expedition
	}
	return ""
}

func (x *Resi) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Resi) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Resi) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resi) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

type CreateResiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingNum   string                 `protobuf:"bytes,1,opt,name=tracking_num,json=trackingNum,proto3" json:"tracking_num,omitempty"`
	Expedition    string                 `protobuf:"bytes,2,opt,name=expedition,proto3" json:"expedition,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PackageName   string                 `protobuf:"bytes,4,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResiRequest) Reset() {
	*x = CreateResiRequest{}
	mi := &file_app_protos_resi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResiRequest) ProtoMessage() {}

func (x *CreateResiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResiRequest.ProtoReflect.Descriptor instead.
func (*CreateResiRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResiRequest) GetTrackingNum() string {
	if x != nil {
		return x.TrackingNum
	}
	return ""
}

func (x *CreateResiRequest) GetExpedition() string {
	if x != nil {
		return x.Expedition
	}
	return ""
}

func (x *CreateResiRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateResiRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

type GetResiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingNum   string                 `protobuf:"bytes,1,opt,name=tracking_num,json=trackingNum,proto3" json:"tracking_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResiRequest) Reset() {
	*x = GetResiRequest{}
	mi := &file_app_protos_resi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResiRequest) ProtoMessage() {}

func (x *GetResiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResiRequest.ProtoReflect.Descriptor instead.
func (*GetResiRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{2}
}

func (x *GetResiRequest) GetTrackingNum() string {
	if x != nil {
		return x.TrackingNum
	}
	return ""
}

type UpdateResiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingNum   string                 `protobuf:"bytes,2,opt,name=tracking_num,json=trackingNum,proto3" json:"tracking_num,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResiRequest) Reset() {
	*x = UpdateResiRequest{}
	mi := &file_app_protos_resi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResiRequest) ProtoMessage() {}

func (x *UpdateResiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResiRequest.ProtoReflect.Descriptor instead.
func (*UpdateResiRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResiRequest) GetTrackingNum() string {
	if x != nil {
		return x.TrackingNum
	}
	return ""
}

func (x *UpdateResiRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteResiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingNum   string                 `protobuf:"bytes,1,opt,name=tracking_num,json=trackingNum,proto3" json:"tracking_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResiRequest) Reset() {
	*x = DeleteResiRequest{}
	mi := &file_app_protos_resi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResiRequest) ProtoMessage() {}

func (x *DeleteResiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResiRequest.ProtoReflect.Descriptor instead.
func (*DeleteResiRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResiRequest) GetTrackingNum() string {
	if x != nil {
		return x.TrackingNum
	}
	return ""
}

type ResiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resi          *Resi                  `protobuf:"bytes,1,opt,name=resi,proto3" json:"resi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResiResponse) Reset() {
	*x = ResiResponse{}
	mi := &file_app_protos_resi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiResponse) ProtoMessage() {}

func (x *ResiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiResponse.ProtoReflect.Descriptor instead.
func (*ResiResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{5}
}

func (x *ResiResponse) GetResi() *Resi {
	if x != nil {
		return x.Resi
	}
	return nil
}

type DeleteResiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResiResponse) Reset() {
	*x = DeleteResiResponse{}
	mi := &file_app_protos_resi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResiResponse) ProtoMessage() {}

func (x *DeleteResiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResiResponse.ProtoReflect.Descriptor instead.
func (*DeleteResiResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResiListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resis         []*Resi                `protobuf:"bytes,1,rep,name=resis,proto3" json:"resis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResiListResponse) Reset() {
	*x = ResiListResponse{}
	mi := &file_app_protos_resi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiListResponse) ProtoMessage() {}

func (x *ResiListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiListResponse.ProtoReflect.Descriptor instead.
func (*ResiListResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{7}
}

func (x *ResiListResponse) GetResis() []*Resi {
	if x != nil {
		return x.Resis
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_protos_resi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{8}
}

type CheckAllResiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllResiResponse) Reset() {
	*x = CheckAllResiResponse{}
	mi := &file_app_protos_resi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllResiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllResiResponse) ProtoMessage() {}

func (x *CheckAllResiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_resi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllResiResponse.ProtoReflect.Descriptor instead.
func (*CheckAllResiResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_resi_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAllResiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_app_protos_resi_proto protoreflect.FileDescriptor

var file_app_protos_resi_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0xc4, 0x01, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x4e, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x30, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x52, 0x04, 0x72, 0x65, 0x73, 0x69, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x69, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x72,
	0x65, 0x73, 0x69, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x52, 0x05, 0x72, 0x65, 0x73, 0x69, 0x73, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xfd, 0x02, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x69, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69,
	0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x69, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x69, 0x12, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x6f,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_protos_resi_proto_rawDescOnce sync.Once
	file_app_protos_resi_proto_rawDescData = file_app_protos_resi_proto_rawDesc
)

func file_app_protos_resi_proto_rawDescGZIP() []byte {
	file_app_protos_resi_proto_rawDescOnce.Do(func() {
		file_app_protos_resi_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protos_resi_proto_rawDescData)
	})
	return file_app_protos_resi_proto_rawDescData
}

var file_app_protos_resi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_protos_resi_proto_goTypes = []any{
	(*Resi)(nil),                 // 0: protos.Resi
	(*CreateResiRequest)(nil),    // 1: protos.CreateResiRequest
	(*GetResiRequest)(nil),       // 2: protos.GetResiRequest
	(*UpdateResiRequest)(nil),    // 3: protos.UpdateResiRequest
	(*DeleteResiRequest)(nil),    // 4: protos.DeleteResiRequest
	(*ResiResponse)(nil),         // 5: protos.ResiResponse
	(*DeleteResiResponse)(nil),   // 6: protos.DeleteResiResponse
	(*ResiListResponse)(nil),     // 7: protos.ResiListResponse
	(*Empty)(nil),                // 8: protos.Empty
	(*CheckAllResiResponse)(nil), // 9: protos.CheckAllResiResponse
}
var file_app_protos_resi_proto_depIdxs = []int32{
	0, // 0: protos.ResiResponse.resi:type_name -> protos.Resi
	0, // 1: protos.ResiListResponse.resis:type_name -> protos.Resi
	1, // 2: protos.ResiService.CreateResi:input_type -> protos.CreateResiRequest
	2, // 3: protos.ResiService.GetResi:input_type -> protos.GetResiRequest
	3, // 4: protos.ResiService.UpdateResi:input_type -> protos.UpdateResiRequest
	4, // 5: protos.ResiService.DeleteResi:input_type -> protos.DeleteResiRequest
	8, // 6: protos.ResiService.GetAllResi:input_type -> protos.Empty
	8, // 7: protos.ResiService.CheckAllResi:input_type -> protos.Empty
	5, // 8: protos.ResiService.CreateResi:output_type -> protos.ResiResponse
	5, // 9: protos.ResiService.GetResi:output_type -> protos.ResiResponse
	5, // 10: protos.ResiService.UpdateResi:output_type -> protos.ResiResponse
	6, // 11: protos.ResiService.DeleteResi:output_type -> protos.DeleteResiResponse
	7, // 12: protos.ResiService.GetAllResi:output_type -> protos.ResiListResponse
	9, // 13: protos.ResiService.CheckAllResi:output_type -> protos.CheckAllResiResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_protos_resi_proto_init() }
func file_app_protos_resi_proto_init() {
	if File_app_protos_resi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protos_resi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_protos_resi_proto_goTypes,
		DependencyIndexes: file_app_protos_resi_proto_depIdxs,
		MessageInfos:      file_app_protos_resi_proto_msgTypes,
	}.Build()
	File_app_protos_resi_proto = out.File
	file_app_protos_resi_proto_rawDesc = nil
	file_app_protos_resi_proto_goTypes = nil
	file_app_protos_resi_proto_depIdxs = nil
}
