// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: app/protos/resi.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResiService_CreateResi_FullMethodName   = "/protos.ResiService/CreateResi"
	ResiService_GetResi_FullMethodName      = "/protos.ResiService/GetResi"
	ResiService_UpdateResi_FullMethodName   = "/protos.ResiService/UpdateResi"
	ResiService_DeleteResi_FullMethodName   = "/protos.ResiService/DeleteResi"
	ResiService_GetAllResi_FullMethodName   = "/protos.ResiService/GetAllResi"
	ResiService_CheckAllResi_FullMethodName = "/protos.ResiService/CheckAllResi"
)

// ResiServiceClient is the client API for ResiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResiServiceClient interface {
	CreateResi(ctx context.Context, in *CreateResiRequest, opts ...grpc.CallOption) (*ResiResponse, error)
	GetResi(ctx context.Context, in *GetResiRequest, opts ...grpc.CallOption) (*ResiResponse, error)
	UpdateResi(ctx context.Context, in *UpdateResiRequest, opts ...grpc.CallOption) (*ResiResponse, error)
	DeleteResi(ctx context.Context, in *DeleteResiRequest, opts ...grpc.CallOption) (*DeleteResiResponse, error)
	GetAllResi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResiListResponse, error)
	CheckAllResi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckAllResiResponse, error)
}

type resiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResiServiceClient(cc grpc.ClientConnInterface) ResiServiceClient {
	return &resiServiceClient{cc}
}

func (c *resiServiceClient) CreateResi(ctx context.Context, in *CreateResiRequest, opts ...grpc.CallOption) (*ResiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiResponse)
	err := c.cc.Invoke(ctx, ResiService_CreateResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiServiceClient) GetResi(ctx context.Context, in *GetResiRequest, opts ...grpc.CallOption) (*ResiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiResponse)
	err := c.cc.Invoke(ctx, ResiService_GetResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiServiceClient) UpdateResi(ctx context.Context, in *UpdateResiRequest, opts ...grpc.CallOption) (*ResiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiResponse)
	err := c.cc.Invoke(ctx, ResiService_UpdateResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiServiceClient) DeleteResi(ctx context.Context, in *DeleteResiRequest, opts ...grpc.CallOption) (*DeleteResiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResiResponse)
	err := c.cc.Invoke(ctx, ResiService_DeleteResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiServiceClient) GetAllResi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResiListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiListResponse)
	err := c.cc.Invoke(ctx, ResiService_GetAllResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiServiceClient) CheckAllResi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckAllResiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAllResiResponse)
	err := c.cc.Invoke(ctx, ResiService_CheckAllResi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResiServiceServer is the server API for ResiService service.
// All implementations must embed UnimplementedResiServiceServer
// for forward compatibility.
type ResiServiceServer interface {
	CreateResi(context.Context, *CreateResiRequest) (*ResiResponse, error)
	GetResi(context.Context, *GetResiRequest) (*ResiResponse, error)
	UpdateResi(context.Context, *UpdateResiRequest) (*ResiResponse, error)
	DeleteResi(context.Context, *DeleteResiRequest) (*DeleteResiResponse, error)
	GetAllResi(context.Context, *Empty) (*ResiListResponse, error)
	CheckAllResi(context.Context, *Empty) (*CheckAllResiResponse, error)
	mustEmbedUnimplementedResiServiceServer()
}

// UnimplementedResiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResiServiceServer struct{}

func (UnimplementedResiServiceServer) CreateResi(context.Context, *CreateResiRequest) (*ResiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResi not implemented")
}
func (UnimplementedResiServiceServer) GetResi(context.Context, *GetResiRequest) (*ResiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResi not implemented")
}
func (UnimplementedResiServiceServer) UpdateResi(context.Context, *UpdateResiRequest) (*ResiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResi not implemented")
}
func (UnimplementedResiServiceServer) DeleteResi(context.Context, *DeleteResiRequest) (*DeleteResiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResi not implemented")
}
func (UnimplementedResiServiceServer) GetAllResi(context.Context, *Empty) (*ResiListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllResi not implemented")
}
func (UnimplementedResiServiceServer) CheckAllResi(context.Context, *Empty) (*CheckAllResiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAllResi not implemented")
}
func (UnimplementedResiServiceServer) mustEmbedUnimplementedResiServiceServer() {}
func (UnimplementedResiServiceServer) testEmbeddedByValue()                     {}

// UnsafeResiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResiServiceServer will
// result in compilation errors.
type UnsafeResiServiceServer interface {
	mustEmbedUnimplementedResiServiceServer()
}

func RegisterResiServiceServer(s grpc.ServiceRegistrar, srv ResiServiceServer) {
	// If the following call pancis, it indicates UnimplementedResiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResiService_ServiceDesc, srv)
}

func _ResiService_CreateResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).CreateResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_CreateResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).CreateResi(ctx, req.(*CreateResiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiService_GetResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).GetResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_GetResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).GetResi(ctx, req.(*GetResiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiService_UpdateResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).UpdateResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_UpdateResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).UpdateResi(ctx, req.(*UpdateResiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiService_DeleteResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).DeleteResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_DeleteResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).DeleteResi(ctx, req.(*DeleteResiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiService_GetAllResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).GetAllResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_GetAllResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).GetAllResi(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiService_CheckAllResi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiServiceServer).CheckAllResi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiService_CheckAllResi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiServiceServer).CheckAllResi(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ResiService_ServiceDesc is the grpc.ServiceDesc for ResiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ResiService",
	HandlerType: (*ResiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResi",
			Handler:    _ResiService_CreateResi_Handler,
		},
		{
			MethodName: "GetResi",
			Handler:    _ResiService_GetResi_Handler,
		},
		{
			MethodName: "UpdateResi",
			Handler:    _ResiService_UpdateResi_Handler,
		},
		{
			MethodName: "DeleteResi",
			Handler:    _ResiService_DeleteResi_Handler,
		},
		{
			MethodName: "GetAllResi",
			Handler:    _ResiService_GetAllResi_Handler,
		},
		{
			MethodName: "CheckAllResi",
			Handler:    _ResiService_CheckAllResi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/protos/resi.proto",
}
